color1 = #cc241d
color2 = #98971a
color3 = #d79921
color4 = #458588
color5 = #b16286
color6 = #689d6a
color7 = #a89984

color8 = #928274
color9 = #fb4934
color10 = #b8bb26
color11 = #fabd2f
color12 = #83a598
color13 = #d3869b
color14 = #8ec07c

orange1 = #d65d0e
orange2 = #fe8019
# bg0 = bg0_h
bg0 = #0d0e0e
bg1 = #121314
bg2 = #1d2021
bg3 = #3c3836
bg4 = #504945
bg5 = #665c54
bg6 = #7c6f64

fg0 = #fbf1c7
fg1 = #ebdbb2
fg2 = #d5c4a1
fg3 = #bdae93
fg4 = #a89984

background = #121314
foreground = #ebdbb2

clr_constant    =   ${color5}
clr_string      =   ${color122}
clr_identifier  =   ${color6}
clr_variable    =   ${foreground}
clr_function    =   ${color14}
clr_statement   =   ${color9}
clr_operator    =   ${color3}
clr_delimiter   =   ${color4}
clr_parameter   =   ${color11}
clr_type        =   ${color3}
clr_storage_class=  ${color155}
clr_keyword     =   ${color9}
clr_comment     =   ${bg5}
clr_special     =   ${orange1}


[waybar]
[kitty]
[vscode]
[hyprland]
[nvim]
[mako]
[hypr]

[hyprpaper]
file = "~/wallpapers/gruvbox_astronaut.png"
