fg0 = ${color254}
fg1 = ${color252}
fg2 = ${color250}
fg3 = ${color248}
fg4 = ${color246}
fg5 = ${color244}

bg0 = ${color232}
bg1 = ${color234}
bg2 = ${color236}
bg3 = ${color238}
bg4 = ${color240}
bg5 = ${color242}

accent = ${color2}
accent2 = ${color3}



#Syntax color


clr_constant    =   ${green}
clr_string      =   ${color122}
clr_identifier  =   ${color4}
clr_variable    =   ${foreground}
clr_function    =   ${color5}
clr_statement   =   ${color9}
clr_operator    =   ${color6}
clr_delimiter   =   ${color6}
clr_parameter   =   ${color11}
clr_type        =   ${color3}
clr_storage_class=  ${color155}
clr_keyword     =   ${color13}
clr_comment     =   ${bg4}
clr_special     =   ${color4}

#Nvim tree
clr_nv_tree_git_ignored =   ${bg3}
clr_nv_tree_exec_file   =   ${foreground}
clr_nv_tree_iamge_file  =   ${color14}
