
anchor=top-center
default-timeout=5000




text-color=#${foreground}
background-color=#${background}a0

border-size=2
border-radius=10
text-alignment=center

[urgency="low"]
border-color=#${accent}

[urgency="normal"]
border-color=#${accent}

[urgency="critical"]
border-color=#${color1}
