#pragma once
#include <string>
#include <array>

inline const std::string APP_NAME = "thync"; 

inline const std::string DEFAULT_PATH       = "${output_dir}/${section_name}";
inline const std::string DEFAULT_FORMAT     = "${color_name} #${color_value}";
inline const std::string DEFAULT_FORMAT_ID  = "${color_name} #${color_value}";
inline const std::string DEFAULT_COMMENT    = "#";
inline const std::string DEFAULT_MODE       = "modify-add";

inline const std::array<std::string, 2> CONFIG_VARIABLES {
    "section_name",
    "output_dir"
};

inline const std::array<std::string, 3> COLOR_VARIABLES {

    "color_name",
    "color_id",
    "color_value"

};

inline const std::string DEFAULT_CONFIG{

    "# Autogenerated default config\n"
    "\n"
    "[default]\n"
    "path = " + DEFAULT_PATH + "\n"
    "format = " + DEFAULT_FORMAT + "\n"
    "format_id = " + DEFAULT_FORMAT_ID + "\n"
    "comment = " + DEFAULT_COMMENT
};

inline const std::string COLORS[] {
    "black",
    "red",
    "green",
    "yellow",
    "blue",
    "magenta",
    "cyan",
    "white",

    "bright_black",
    "bright_red",
    "bright_green",
    "bright_yellow",
    "bright_blue",
    "bright_magenta",
    "bright_cyan",
    "bright_white"
};

inline const std::string HELP{

    "Usage\n\n"
    "\tthync [options] <color-file-name> <output-dir>\n\n"
    "First argument that doesn't belong to any option goes to <color-file-name>, the second\n"
    "to <output-dir>. <output-dir> defaults to local config folder, checks performed in order: \n"
    "\t$XDG_CONFIG_HOME\n"
    "\t$HOME/.config\n\n"
    "Options:\n"
    "\t -o <output-dir> \t\t = Override output directory\n"
    "\t -f <file-name>  \t\t = Color config path\n"
    "\t --preview, -p \t\t\t = renders the generated colors (doesn't generate any files!)\n"
    "\t --preview-gen, -P \t\t = renders the generated palette (doesn't generate any files!)\n"
    "\t --help, -h \t\t\t = shows this help\n\n"

};

inline const std::string CONFIG_HEADER{
    "#\tAutogenerated config\n"
    "#\tFor more info check https://github.com/loytech825/thync \n"
    "#\tDefault preset last updated 6.6.2026\n"
    "\n"
};

inline const std::string DEFAULT_CONFIG_FORMAT{
    CONFIG_HEADER +
    "#\tRegular colors:\n"

    //colors stored in numbers so no additional conversin is required
    "${key=0}\n"
    "${key=1}\n"
    "${key=2}\n"
    "${key=3}\n"
    "${key=4}\n"
    "${key=5}\n"
    "${key=6}\n"
    "${key=7}\n"

    "${key=8}\n"
    "${key=9}\n"
    "${key=10}\n"
    "${key=11}\n"
    "${key=12}\n"
    "${key=13}\n"
    "${key=14}\n"
    "${key=15}\n"
    "\n"
    "#Background and foreground\n"
    "${key=background}\n"
    "${key=foreground}\n"
    "\n"
    "#Custom colors\n"
};
